# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ebrahim/vivado/Lab1/mixed_approach/mixed_approach.srcs/sources_1/bd/Lab1_sf/ip/Lab1_sf_auto_pc_0/Lab1_sf_auto_pc_0.xci
# IP: The module: 'Lab1_sf_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ebrahim/vivado/Lab1/mixed_approach/mixed_approach.srcs/sources_1/bd/Lab1_sf/ip/Lab1_sf_auto_pc_0/Lab1_sf_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab1_sf_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/ebrahim/vivado/Lab1/mixed_approach/mixed_approach.srcs/sources_1/bd/Lab1_sf/ip/Lab1_sf_auto_pc_0/Lab1_sf_auto_pc_0.xci
# IP: The module: 'Lab1_sf_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ebrahim/vivado/Lab1/mixed_approach/mixed_approach.srcs/sources_1/bd/Lab1_sf/ip/Lab1_sf_auto_pc_0/Lab1_sf_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab1_sf_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
