# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ebrahim/vivado/Lab1/opcional1/zyboVGA.xdc

# Block Designs: bd/lab1_ob/lab1_ob.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_ob || ORIG_REF_NAME==lab1_ob}]

# IP: bd/lab1_ob/ip/lab1_ob_processing_system7_0_0/lab1_ob_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_ob_processing_system7_0_0 || ORIG_REF_NAME==lab1_ob_processing_system7_0_0}]

# IP: bd/lab1_ob/ip/lab1_ob_axi_gpio_0_0/lab1_ob_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_ob_axi_gpio_0_0 || ORIG_REF_NAME==lab1_ob_axi_gpio_0_0}]

# IP: bd/lab1_ob/ip/lab1_ob_axi_gpio_0_1/lab1_ob_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_ob_axi_gpio_0_1 || ORIG_REF_NAME==lab1_ob_axi_gpio_0_1}]

# IP: bd/lab1_ob/ip/lab1_ob_axi_gpio_0_2/lab1_ob_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_ob_axi_gpio_0_2 || ORIG_REF_NAME==lab1_ob_axi_gpio_0_2}]

# IP: bd/lab1_ob/ip/lab1_ob_axi_gpio_0_3/lab1_ob_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_ob_axi_gpio_0_3 || ORIG_REF_NAME==lab1_ob_axi_gpio_0_3}]

# IP: bd/lab1_ob/ip/lab1_ob_ypos_0/lab1_ob_ypos_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_ob_ypos_0 || ORIG_REF_NAME==lab1_ob_ypos_0}]

# IP: bd/lab1_ob/ip/lab1_ob_ps7_0_axi_periph_0/lab1_ob_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_ob_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab1_ob_ps7_0_axi_periph_0}]

# IP: bd/lab1_ob/ip/lab1_ob_rst_ps7_0_50M_0/lab1_ob_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_ob_rst_ps7_0_50M_0 || ORIG_REF_NAME==lab1_ob_rst_ps7_0_50M_0}]

# IP: bd/lab1_ob/ip/lab1_ob_VGA_SYNC_0_0/lab1_ob_VGA_SYNC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_ob_VGA_SYNC_0_0 || ORIG_REF_NAME==lab1_ob_VGA_SYNC_0_0}]

# IP: bd/lab1_ob/ip/lab1_ob_screen_object_0_0/lab1_ob_screen_object_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_ob_screen_object_0_0 || ORIG_REF_NAME==lab1_ob_screen_object_0_0}]

# IP: bd/lab1_ob/ip/lab1_ob_xbar_0/lab1_ob_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_ob_xbar_0 || ORIG_REF_NAME==lab1_ob_xbar_0}]

# IP: bd/lab1_ob/ip/lab1_ob_auto_pc_0/lab1_ob_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_ob_auto_pc_0 || ORIG_REF_NAME==lab1_ob_auto_pc_0}]

# XDC: bd/lab1_ob/lab1_ob_ooc.xdc
