# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ebrahim/vivado/Lab1/zyboVGA.xdc

# Block Designs: bd/Lab1_sf/Lab1_sf.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_sf || ORIG_REF_NAME==Lab1_sf}]

# IP: bd/Lab1_sf/ip/Lab1_sf_processing_system7_0_2/Lab1_sf_processing_system7_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_sf_processing_system7_0_2 || ORIG_REF_NAME==Lab1_sf_processing_system7_0_2}]

# IP: bd/Lab1_sf/ip/Lab1_sf_axi_gpio_0_0/Lab1_sf_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_sf_axi_gpio_0_0 || ORIG_REF_NAME==Lab1_sf_axi_gpio_0_0}]

# IP: bd/Lab1_sf/ip/Lab1_sf_axi_gpio_0_1/Lab1_sf_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_sf_axi_gpio_0_1 || ORIG_REF_NAME==Lab1_sf_axi_gpio_0_1}]

# IP: bd/Lab1_sf/ip/Lab1_sf_ps7_0_axi_periph_0/Lab1_sf_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_sf_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab1_sf_ps7_0_axi_periph_0}]

# IP: bd/Lab1_sf/ip/Lab1_sf_rst_ps7_0_50M_0/Lab1_sf_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_sf_rst_ps7_0_50M_0 || ORIG_REF_NAME==Lab1_sf_rst_ps7_0_50M_0}]

# IP: bd/Lab1_sf/ip/Lab1_sf_VGA_SYNC_0_0/Lab1_sf_VGA_SYNC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_sf_VGA_SYNC_0_0 || ORIG_REF_NAME==Lab1_sf_VGA_SYNC_0_0}]

# IP: bd/Lab1_sf/ip/Lab1_sf_xbar_0/Lab1_sf_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_sf_xbar_0 || ORIG_REF_NAME==Lab1_sf_xbar_0}]

# IP: bd/Lab1_sf/ip/Lab1_sf_screen_object_0_0/Lab1_sf_screen_object_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_sf_screen_object_0_0 || ORIG_REF_NAME==Lab1_sf_screen_object_0_0}]

# IP: bd/Lab1_sf/ip/Lab1_sf_xlconstant_0_0/Lab1_sf_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_sf_xlconstant_0_0 || ORIG_REF_NAME==Lab1_sf_xlconstant_0_0}]

# IP: bd/Lab1_sf/ip/Lab1_sf_readRow_0/Lab1_sf_readRow_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_sf_readRow_0 || ORIG_REF_NAME==Lab1_sf_readRow_0}]

# IP: bd/Lab1_sf/ip/Lab1_sf_auto_pc_0/Lab1_sf_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab1_sf_auto_pc_0 || ORIG_REF_NAME==Lab1_sf_auto_pc_0}]

# XDC: bd/Lab1_sf/Lab1_sf_ooc.xdc
