# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ebrahim/vivado/Lab1/opcional1/Lab_ob/Lab_ob.srcs/sources_1/bd/lab1_ob/ip/lab1_ob_axi_gpio_0_2/lab1_ob_axi_gpio_0_2.xci
# IP: The module: 'lab1_ob_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ebrahim/vivado/Lab1/opcional1/Lab_ob/Lab_ob.srcs/sources_1/bd/lab1_ob/ip/lab1_ob_axi_gpio_0_2/lab1_ob_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab1_ob_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/ebrahim/vivado/Lab1/opcional1/Lab_ob/Lab_ob.srcs/sources_1/bd/lab1_ob/ip/lab1_ob_axi_gpio_0_2/lab1_ob_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab1_ob_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/ebrahim/vivado/Lab1/opcional1/Lab_ob/Lab_ob.srcs/sources_1/bd/lab1_ob/ip/lab1_ob_axi_gpio_0_2/lab1_ob_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab1_ob_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/ebrahim/vivado/Lab1/opcional1/Lab_ob/Lab_ob.srcs/sources_1/bd/lab1_ob/ip/lab1_ob_axi_gpio_0_2/lab1_ob_axi_gpio_0_2.xci
# IP: The module: 'lab1_ob_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ebrahim/vivado/Lab1/opcional1/Lab_ob/Lab_ob.srcs/sources_1/bd/lab1_ob/ip/lab1_ob_axi_gpio_0_2/lab1_ob_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab1_ob_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/ebrahim/vivado/Lab1/opcional1/Lab_ob/Lab_ob.srcs/sources_1/bd/lab1_ob/ip/lab1_ob_axi_gpio_0_2/lab1_ob_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab1_ob_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/ebrahim/vivado/Lab1/opcional1/Lab_ob/Lab_ob.srcs/sources_1/bd/lab1_ob/ip/lab1_ob_axi_gpio_0_2/lab1_ob_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab1_ob_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
